project_id = "voypgvppnnmacbjboovn"

[functions.process-recording]
verify_jwt = true

[functions.chat-with-persona]
verify_jwt = true

[functions.create-voice-session]
verify_jwt = true

[functions.clone-voice]
verify_jwt = true

[functions.generate-speech]
verify_jwt = true

[functions.retry-recording-processing]
verify_jwt = true

[functions.test-openai]
verify_jwt = false

[functions.test-elevenlabs]
verify_jwt = false

[functions.debug-audio]
verify_jwt = false