project_id = "voypgvppnnmacbjboovn"

[functions.process-recording]
verify_jwt = false

[functions.chat-with-persona]
verify_jwt = false

[functions.create-voice-session]
verify_jwt = false

[functions.clone-voice]
verify_jwt = false

[functions.generate-speech]
verify_jwt = false