// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voypgvppnnmacbjboovn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveXBndnBwbm5tYWNiamJvb3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDczNDMsImV4cCI6MjA2OTc4MzM0M30.73AUb2zvktuOnWXQq3WUgPMN3nwNAoHFCd-D2C0TgIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});